#!/usr/bin/env bash
#
# Record the integration tests one at a time and file the recordings under a
# directory per test file, the layout the shared recordings in the conductor
# repository use (one folder per example there).
#
#   record-suite.sh <recordings-dir> [go-test-regex]
#
# The server must already be running in record mode on <recordings-dir>:
#
#   conductor-server.sh record test/integration_tests/ai/testdata/llm-recordings
#
# The recorder names files by UUID and knows nothing about tests, so this
# script runs each test alone, then moves the files that appeared at the top
# of <recordings-dir> into <recordings-dir>/<test file>/, where <test file> is
# the test's source file without _test.go (mcp_test.go records under mcp/).
# It ends by writing <recordings-dir>/INDEX.md, one line per recording: the
# agent's tools and the first user message. Playback loads the directory
# recursively, so the whole tree replays in one server run.
#
# Any environment the tests need (CONDUCTOR_SERVER_URL, CONDUCTOR_E2E_SECRET_PROVISIONED,
# CONDUCTOR_AGENT_LLM_MODEL) is passed through unchanged.
set -euo pipefail

dir="${1:?usage: record-suite.sh <recordings-dir> [go-test-regex]}"
pattern="${2:-.}"
here="$(cd "$(dirname "$0")/.." && pwd)"
dir="$(mkdir -p "$dir" && cd "$dir" && pwd)"
: "${CONDUCTOR_SERVER_URL:?CONDUCTOR_SERVER_URL must point at the recording server}"

cd "$here"
tests=$(go test -tags integration -list "$pattern" . | grep '^Test' || true)
[[ -n "$tests" ]] || { echo "no tests match $pattern" >&2; exit 1; }

snapshot() { find "$dir" -maxdepth 1 -name '*.json' -newer "$1" 2>/dev/null; }

for t in $tests; do
  mark=$(mktemp)
  echo "=== $t"
  go test -tags integration -count=1 -run "^${t}\$" . 2>&1 | grep -E '^(--- |ok|FAIL|\s+\S+_test\.go)' || true
  new=$(snapshot "$mark")
  rm -f "$mark"
  if [[ -n "$new" ]]; then
    src=$(grep -l -E "^func ${t}\(" ./*_test.go | head -1)
    group=$(basename "${src:-$t}" _test.go)
    mkdir -p "$dir/$group"
    echo "$new" | xargs -I{} mv {} "$dir/$group/"
    echo "    $(echo "$new" | wc -l | tr -d ' ') recording(s) -> $group/"
  else
    echo "    no LLM calls recorded"
  fi
done

python3 - "$dir" <<'PY'
import json, os, sys
root = sys.argv[1]
import re
here = os.getcwd()
lines = ["# Recordings by test file", "",
         "Generated by scripts/record-suite.sh. One directory per test file, named after",
         "the file without _test.go; each recording is one LLM response the server saved",
         "while a test in that file ran.", ""]
for group in sorted(d for d in os.listdir(root) if os.path.isdir(os.path.join(root, d))):
    files = sorted(f for f in os.listdir(os.path.join(root, group)) if f.endswith(".json"))
    source = os.path.join(here, group + "_test.go")
    tests = re.findall(r"^func (Test\w+)\(", open(source).read(), re.M) if os.path.exists(source) else []
    lines.append(f"## {group} ({len(files)})")
    lines.append("")
    if tests:
        lines.append("Tests: " + ", ".join(tests))
        lines.append("")
    for f in files:
        d = json.load(open(os.path.join(root, group, f)))
        r = d["request"]
        tools = ", ".join(t["name"] for t in r["tools"]) or "none"
        user = next((m["text"] for m in r["messages"] if m["role"] == "user"), "").split("\n")[0]
        lines.append(f"- `{f}`: {len(r['messages'])} messages; tools: {tools}; user: {user[:90]!r}")
    lines.append("")
open(os.path.join(root, "INDEX.md"), "w").write("\n".join(lines))
print("wrote", os.path.join(root, "INDEX.md"))
PY
