#!/usr/bin/env bash
#
# Record the ai_e2e tests one at a time and file each test's recordings under
# its own directory, so a reader can tell which test produced which file.
#
#   record-suite.sh <recordings-dir> [go-test-regex]
#
# The server must already be running in record mode on <recordings-dir>:
#
#   conductor-server.sh record test/ai_e2e/testdata/llm-recordings/suite
#
# The recorder names files by UUID and knows nothing about tests, so this
# script runs each test alone, then moves the files that appeared at the top
# of <recordings-dir> into <recordings-dir>/<TestName>/. It ends by writing
# <recordings-dir>/INDEX.md, one line per recording: the test, the agent's
# tools, and the first user message. Playback loads the directory
# recursively, so the whole tree still replays in one server run.
#
# Any environment the tests need (CONDUCTOR_SERVER_URL, CONDUCTOR_E2E_SECRET_PROVISIONED,
# CONDUCTOR_AGENT_LLM_MODEL) is passed through unchanged.
set -euo pipefail

dir="${1:?usage: record-suite.sh <recordings-dir> [go-test-regex]}"
pattern="${2:-.}"
here="$(cd "$(dirname "$0")/.." && pwd)"
dir="$(mkdir -p "$dir" && cd "$dir" && pwd)"
: "${CONDUCTOR_SERVER_URL:?CONDUCTOR_SERVER_URL must point at the recording server}"

cd "$here"
tests=$(go test -tags e2e -list "$pattern" . | grep '^Test' || true)
[[ -n "$tests" ]] || { echo "no tests match $pattern" >&2; exit 1; }

snapshot() { find "$dir" -maxdepth 1 -name '*.json' -newer "$1" 2>/dev/null; }

for t in $tests; do
  mark=$(mktemp)
  echo "=== $t"
  go test -tags e2e -count=1 -run "^${t}\$" . 2>&1 | grep -E '^(--- |ok|FAIL|\s+\S+_test\.go)' || true
  new=$(snapshot "$mark")
  rm -f "$mark"
  if [[ -n "$new" ]]; then
    mkdir -p "$dir/$t"
    echo "$new" | xargs -I{} mv {} "$dir/$t/"
    echo "    $(echo "$new" | wc -l | tr -d ' ') recording(s) -> $t/"
  else
    echo "    no LLM calls recorded"
  fi
done

python3 - "$dir" <<'PY'
import json, os, sys
root = sys.argv[1]
lines = ["# Recordings by test", "",
         "Generated by scripts/record-suite.sh. One directory per test; each file is",
         "one LLM response the server recorded while that test ran.", ""]
for test in sorted(d for d in os.listdir(root) if os.path.isdir(os.path.join(root, d))):
    files = sorted(f for f in os.listdir(os.path.join(root, test)) if f.endswith(".json"))
    lines.append(f"## {test} ({len(files)})")
    lines.append("")
    for f in files:
        d = json.load(open(os.path.join(root, test, f)))
        r = d["request"]
        tools = ", ".join(t["name"] for t in r["tools"]) or "none"
        user = next((m["text"] for m in r["messages"] if m["role"] == "user"), "").split("\n")[0]
        lines.append(f"- `{f}`: {len(r['messages'])} messages; tools: {tools}; user: {user[:90]!r}")
    lines.append("")
open(os.path.join(root, "INDEX.md"), "w").write("\n".join(lines))
print("wrote", os.path.join(root, "INDEX.md"))
PY
