name: golangci-lint

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.golangci.yml'

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.3
          only-new-issues: true
          args: --timeout 10m --issues-exit-code=1