name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    permissions:
      contents: read       # minimal read access
      checks: write        # needed for test report annotations

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build ./...

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@v1.12.0

      - name: Run Integration tests 
        run: |
          gotestsum --format testname  --junitfile report.xml -- -v ./test/integration_tests/...
        env:
          CONDUCTOR_SERVER_URL: ${{ secrets.CONDUCTOR_SERVER_URL }}
          CONDUCTOR_AUTH_KEY: ${{ secrets.KEY }}
          CONDUCTOR_AUTH_SECRET: ${{ secrets.SECRET }}

      - name: Run Backward Compatibility Tests
        run: |
          echo "🚀 Starting Backward Compatibility Tests..."
          cd test/backward_compatibility
          chmod +x run_compatibility.sh
          ./run_compatibility.sh
        env:
          CONDUCTOR_SERVER_URL: ${{ secrets.CONDUCTOR_SERVER_URL }}
          CONDUCTOR_AUTH_KEY: ${{ secrets.KEY }}
          CONDUCTOR_AUTH_SECRET: ${{ secrets.SECRET }}

      - name: Publish test results
        if: always() 
        uses: dorny/test-reporter@v1
        with:
          name: Integration tests report
          path: report.xml
          reporter: java-junit
