name: Integration + Backward Compatibility Tests (SM cluster)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests-sm:
    runs-on: ubuntu-latest
    env:
      CONDUCTOR_SERVER_URL: ${{ vars.SERVER_URL }}
      CONDUCTOR_AUTH_KEY: ${{ secrets.AUTH_KEY }}
      CONDUCTOR_AUTH_SECRET: ${{ secrets.AUTH_SECRET }}

    permissions:
      contents: read       # minimal read access
      checks: write        # needed for test report annotations

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build ./...

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@v1.12.0

      - name: Run Integration tests (SM cluster)
        run: |
          gotestsum --format testname  --junitfile report.xml -- -v ./test/integration_tests/...

      - name: Publish test results (SM cluster)
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Integration tests report (SM cluster)
          path: report.xml
          reporter: java-junit

      - name: Run Backward Compatibility Tests (SM cluster)
        run: |
          echo "🚀 Starting Backward Compatibility Tests..."
          cd test/backward_compatibility
          chmod +x run_compatibility.sh
          ./run_compatibility.sh
