name: Lint & Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Go Format and Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.17

      - name: Install formatting tools
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install mvdan.cc/gofumpt@latest

      - name: Run go fmt
        run: go fmt ./...

      - name: Run goimports
        run: goimports -w .

      - name: Run gofumpt (optional stricter formatting)
        run: gofumpt -w .

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.56

      - name: Run golangci-lint
        run: golangci-lint run ./...
